### PR TITLE
add support for mobileDevice REST API parameter

### LINKED ISSUE #74: support mobileDevice REST API parameter
Would be nice to have support for the `mobileDevice` REST API parameter..

from the [docs](https://sites.google.com/a/webpagetest.org/docs/advanced-features/webpagetest-restful-apis)

> Device name from mobile_devices.ini to use for mobile emulation (only when mobile=1 is specified to enable emulation and only for Chrome)

### PR DESCRIPTION
**Pull request by montmanu**
document `--device` option

closes #74

### CODE REVIEW

**Comment by abarre** [comment]
@montmanu, @marcelduran, do you know what prevents the merge of this PR ?
The change is useful to reflect the current API.

**Comment by montmanu** [comment]
@abarre @marcelduran i hadn't looked at the build output until now.. test was failing because of a casing issue in the option description. most recent commit resolved that.

**Comment by montmanu** [comment]
@marcelduran @soulgalore gentle bump.. think this can be merged in now that the tests are passing?

**Comment by soulgalore** [comment]
@montmanu sorry I don't have merge rights :)

**Comment by montmanu** [comment]
thanks all!

**Pull request merged**
